LEARNING_EXTERNAL_TRAINING_SETUP_SAVE_ID = '//input[@type="submit"]'

LEARNING_ADD_EXTERNAL_TRAINING_BUTTON_ID = '//a[@href="/learning/external-training/edit"]'

# desc disabled id =elmo_learningbundle_external_training_description
# desc optional/reqd id =elmo_learningbundle_external_training_descriptionRequired
#
# elmo_learningbundle_external_training_completionDate
# elmo_learningbundle_external_training_completionDateRequired
#
#elmo_learningbundle_external_training_expiryDate
# elmo_learningbundle_external_training_expiryDateRequired
#
# elmo_learningbundle_external_training_duration
# elmo_learningbundle_external_training_durationRequired
#
# elmo_learningbundle_external_training_score
# elmo_learningbundle_external_training_scoreRequired
#
# elmo_learningbundle_external_training_cpdPoints
# elmo_learningbundle_external_training_cpdPointsRequired
#
# elmo_learningbundle_external_training_attachment
# elmo_learningbundle_external_training_attachmentRequired
#
# elmo_learningbundle_external_training_comment
# elmo_learningbundle_external_training_commentRequired
#
# :id, 'elmo_learningbundle_external_training_libraryOnly'