MAIN_DASHBOARD = "//a[@href='/au/dashboard/home']"
ADHOC_DASHBOARD = "//a[@href='/sp/dashboard/adhocs']"
PAY_CYCLE_CLASS_NAME ="dx-dropdowneditor-icon"
NEXT_XPATH ='//*[@id="dashboardContainer"]/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/p/button[2]'
PREVIOUS_XPATH = '//*[@id="dashboardContainer"]/div[2]/div/div[2]/div/div[2]/div[2]/div/div[2]/div[1]/div[2]/p/button[1]'
STATUS_XPATH = "//span[@class='bootstrap-switch-handle-off bootstrap-switch-success']"
GENERATE_PAYSLIPS_XPATH = "//div[contains(text(),'Generate payslips')]"
CLK_GENERATE_PAYSLIPS_XPATH = "//button[contains(text(),'Generate Payslips')]"
DISTR_PAYSLIPS_XPATH = "//div[contains(text(),'Distribute payslips')]"
VIEW_ALL_PAYSLIPS_XPATH = "//div[contains(text(),'View All payslips')]"
SEND_ENABLED_XPATH = "//button[@class='btn elmo-btn-blue']"
SEND_DISABLED_XPATH = "//div[@class='dx-toolbar-before']//div[@class='dx-item-content dx-toolbar-item-content']"
CONFIRM_SEND_PAYSLIPS_XPATH = "//div[@class='dx-toolbar-center']//div[1]//div[1]//div[1]//div[1]"
COMMIT_PAY_CYCLE_XPATH = "//div[contains(text(),'Commit paycycle')]"
COMMIT_CONFIRM_XPATH = "//button[contains(text(),'Confirm')]"
CONFIRM_USERNAME_XPATH = "//div[@class='col-md-8']//div[1]//div[1]//input[1]"
CONFIRM_PASSWORD_XPATH = "//input[@type='password']"
CONFIRM__XPATH = "//button[contains(text(),'I am ready to commit my pay cycle')]"
ADD_NEW_MEMBER_XPATH = "//div[contains(text(),'Add new member')]"
TERM_MEMBER_XPATH = "//div[contains(text(),'Terminate a member')]"
ENTER_TIMESHEETS_XPATH = "//div[contains(text(),'Enter timesheets')]"
APPROVE_TIMESHEETS_XPATH = "//div[contains(text(),'Approve timesheets')]"
REVIEW_TIMESHEETS_XPATH = "//div[contains(text(),'Review timesheets')]"
ENTER_LEAVE_XPATH = "//div[contains(text(),'Enter leave')]"
APPROVE_LEAVE_XPATH = "//div[contains(text(),'Approve leave')]"
REVIEW_LEAVE_XPATH = "//div[contains(text(),'Review leave')]"
VARIANCE_REPORT_XPATH = "//div[contains(text(),'Variance report by input')]"
PAYROLL_AUDIT_REPORT_XPATH = "//div[contains(text(),'Payroll Audit Report')]"
SUPER_REPORT_XPATH = "//div[contains(text(),'Superannuation report')]"
PAYG_REPORT_XPATH = "//div[contains(text(),'PAYG report')]"
EMP_PAY_ELEMENT_REPORT_XPATH = "//div[contains(text(),'Employee pay element report')]"
TERMINATION_REPORT_XPATH = "//div[contains(text(),'Termination report')]"
EFT_REPORT_XPATH = "//div[contains(text(),'EFT report')]"
CREATE_ABA_XPATH = "//div[contains(text(),'Create ABA')]"
GENERAL_LEDGER_REPORT_XPATH = "//div[contains(text(),'General ledger report')]"
PAY_CYCLE_CLEAR_CSS = 'input[role="combobox"]'
PAYMENT_DATE_CLASS = 'widget-thumb-body'
CONFIRM_LOGIN_DETAILS_XPATH = "//div[@class='modal-header']//button[@type='button']"