ELMO_CONFIG_USER_ACTIVATION_ON_ID = "//select[contains(@id,'elmoConfiguration_userActivationOn')]"
ELMO_CONFIG_NOTIFY_NEW_USER_ID = "//select[contains(@id,'elmoConfiguration_userAutoNotify')]"
ELMO_CONFIG_EMPLOYEE_MUST_HAVE_MANAGER_ID = "//select[contains(@id,'elmoConfiguration_selectManager')]"
ELMO_CONFIG_LOCK_COURSE_WITH_ENROLMENTS_ID = "//select[contains(@id,'elmoConfiguration_lockCourseWithEnrolments')]"
ELMO_CONFIG_NEW_USER_CONTRACT = "//select[contains(@id,'elmoConfiguration_newUserContract')]"
ELMO_CONFIG_NEW_OB_USER_CONTRACT = "//select[contains(@id,'elmoConfiguration_newOBUserContract')]"
ELMO_CONFIG_SAVE_ID = "//button[contains(.,'Save')]"