REQUISITION_TAB = "Requisition"
NEW_REQUISITION_BTN = "//button[contains(.,'New Requisition')]"
REQUISITION_POS_INDEX_ARROW = "select2-arrow"
REQUISITION_POS_INDEX_CLASS = "select2-result"
REQUISITION_LOC_INDEX_ARROW = "select2-arrow"
REQUISITION_LOC_INDEX_CLASS = "select2-result"
REQUISITION_NUMBER_OF_POSITION = "//input[@name='numberOfPositions']"
REQUISITION_CALENDER_DUEDATE = "//input[@name='dueDate']"
REQUISITION_CALENDER_DONE_BTN = "//button[@ng-click='isOpen = false']"
REQUISITION_SUBMIT_BTN = "//button[contains(.,'Submit')]"