
ADMIN_PROFILE_DROPDOWN = "dropdown-toggle"
ADMIN_COG = "glyphicon-cog"
SUCCESSION_EXPAND ="Succession"
SUCCESSION_REVIEW_SETUP_PATH = "//span[contains(.,'Succession Review Setup')]"
DROPDOWN = "dropdown-toggle"
NEW_PLAN_BTN ="//button[contains(.,'New Plan')]"
TITLE_ID = 'title'
SAVE_BTN = "//button[contains(.,'Save')]"
SUCCESSION_REVIEW_LINK = "Succession Review Setup"
HIDE_PATH = "/html/body/div[2]/div/div[2]/div[1]/div[1]/table/tbody/tr[4]/td/div/div[2]/div/div[2]/ul/li[2]/a"
SHOW_HIDDEN_BTN = "//button[contains(.,'Show Hidden')]"
VISIBLE_BTN = "//button[@ng-click=' toggleVisible(item, 1)']"
SHOW_VISIBLE_BTN = "//button[contains(.,'Show Visible')]"
SEARCH_FIELD = "//input[@ng-model='search.searchText']"
SEARCH_BTN = "glyphicon-search"
SEARCH_RESULT = "truncate"
MESSAGE_CLASS = "bootbox-body"